#!/usr/bin/env bash
# script that displays information about subdomains

allsubdomains=("www" "lb-01" "web-01" "web-02")
prettify () {
    dig "$subdomain.$domain" | grep -A1 ';; ANSWER SECTION:' | grep -v 'ANSWER' | awk -v awksub="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", awksub, $4, $5}'
}

if [ $# -eq 1 ]
then 
    for a in "${allsubdomains[@]}"
    do
	domain="$1"
	subdomain="$a"
	prettify "$a" "$1"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    prettify "$2" "$1"
fi
