#!/usr/bin/env bash
# if and while

i=1

# Start the while loop
while [[ $i -le 10 ]]
do
	if [[ $i -eq 9 ]]
  	then
    		echo "Best School"
    		echo "Hi"
  	else
    		echo "Best School"
  	fi

  i=$((i+1))
done
