#!/usr/bin/env bash
# to file or not

if [ -f school ]; then
  echo "School file exists"

  if [ -s school ]; then
    echo "School file is not empty"
  else
    echo "School file is empty"
  fi

  if [ -r school ]; then
    echo "School is a regular file"
  fi
else
  echo "School file does not exist"
fi
