#!/usr/bin/env bash
# to file or not

if [ -e school ]; then
  # File exists
  echo "School file exists."

  # Check if the file is empty
  if [ -s school ]; then
    echo "School file is not empty."
  else
    echo "School file is empty."
  fi

  # Check if the file is a regular file
  if [ -f school ]; then
    echo "School is a regular file."
  fi
else
  # File does not exist
  echo "School file does not exist."
fi
